### ISSUE TITLE
package.json中配置了 type: module的时候，无法打包

### ISSUE THREAD

**Issue by guohui666** [fuchengwei/deploy-cli-service#50]
![image](https://github.com/fuchengwei/deploy-cli-service/assets/32350854/2361d649-4dd6-4a36-9fd2-d0d771ccff4e)

配置了 `"type": "module"`的情况下，打包会报错

```
> vue-pure-admin@5.1.0 deploy:test E:\projects\rong-saas
> deploy-cli-service deploy --mode test

E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\commands\deploy.js:291
      const config = require(deployConfigPath)
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\projects\rong-saas\deploy.config.js from E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\commands\deploy.js not supported.   
Instead change the require of deploy.config.js in E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\commands\deploy.js to a dynamic import() which is available in all CommonJS mo
dules.
    at Object.apply (E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\commands\deploy.js:291:22)
    at Command.<anonymous> (E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\service.js:40:19)
    at Command.listener [as _actionHandler] (E:\projects\rong-saas\node_modules\.pnpm\commander@6.2.1\node_modules\commander\index.js:426:31)
    at Command._parseCommand (E:\projects\rong-saas\node_modules\.pnpm\commander@6.2.1\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (E:\projects\rong-saas\node_modules\.pnpm\commander@6.2.1\node_modules\commander\index.js:953:18)
    at Command._parseCommand (E:\projects\rong-saas\node_modules\.pnpm\commander@6.2.1\node_modules\commander\index.js:970:12)
    at Command.parse (E:\projects\rong-saas\node_modules\.pnpm\commander@6.2.1\node_modules\commander\index.js:801:10)
    at Service.run (E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\lib\service.js:13:13)
    at Object.<anonymous> (E:\projects\rong-saas\node_modules\.pnpm\deploy-cli-service@1.4.1\node_modules\deploy-cli-service\bin\deploy-cli-service.js:10:9) {
  code: 'ERR_REQUIRE_ESM'
}

```
百度之后说是由于 Node.js 同时有 Common JS 和 ES6 两套规则导致的

修改源码、把配置改为es module之后可以打包了
node_modules/deploy-cli-service/lib/commands/deploy.js

```
      // const config = require(deployConfigPath) 改为import()
   let module = await import(`file://${deployConfigPath}`)
      const config = module.default
      const cluster = config.cluster
      const projectName = config.projectName
      const currentTime = new Date().getTime()

      const createdEnvConfig = (env) => {
        checkEnvCorrect(config, env)

        return Object.assign(config[env], {
          privateKey: config.privateKey,
          passphrase: config.passphrase,
          readyTimeout: config.readyTimeout
        })
      }
```
```
export default {
  projectName: '', // 项目名称
  passphrase: '',
  test: {
  }
}

```

请问还有什么其他的解决方案吗？

**Comment by drag0n-app** [comment]
我也到这个问题，建议支持deploy.config.cjs文件

**Comment by fuchengwei** [comment]
已修复 升级到最新的 1.5.2 版本即可
配置 type: "module" 后将 deploy.config.js 修改 为 deploy.config.cjs 即可
